// Unified Quote PDF renderer used across approval requests, finance, project, and customer profile
// Renders an HTML-based printable view with consistent styling and correct tax/discount totals

export function renderQuotePdf(quoteData = {}, options = {}) {
  try {
    const data = quoteData || {};
    const items = Array.isArray(data.items) ? data.items : [];
    const rows = items.map((it, i) => `
      <tr>
        <td>${(it.description || `Item ${i+1}`)}</td>
        <td class="num">${Number(it.qty||1)}</td>
        <td class="num">${Number(it.unitPrice||0).toFixed(2)}</td>
        <td class="num">${(Number(it.qty||1)*Number(it.unitPrice||0)).toFixed(2)}</td>
      </tr>`).join('');
    const subtotal = items.reduce((s,it)=> s + Number(it.qty||1)*Number(it.unitPrice||0),0);
    const taxRate = Number(data.taxRate || 0);
    const discount = Number(data.discount || 0);
    const taxAmount = subtotal * (taxRate/100);
    const total = subtotal + taxAmount - discount;
    const today = new Date();
    const dateStr = today.toLocaleDateString();
    const logoUrl = '/proflow-logo.png';
    const title = options.title || data.name || 'Quotation';
    const html = `
      <html>
      <head>
        <meta charset="utf-8"/>
        <title>${title}</title>
        <style>
          *{box-sizing:border-box}
          body{font-family:Arial,Helvetica,sans-serif;color:#111827;margin:0;padding:24px;background:#f9fafb}
          .sheet{width:820px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:24px}
          .header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #e5e7eb;padding-bottom:12px;margin-bottom:16px}
          .brand{display:flex;gap:12px;align-items:center}
          .brand img{height:36px;width:auto}
          .brand h1{font-size:20px;margin:0}
          .meta{font-size:12px;color:#6b7280;text-align:right}
          h2{font-size:18px;margin:12px 0}
          .grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
          .card{border:1px solid #e5e7eb;border-radius:8px;padding:12px}
          table{width:100%;border-collapse:collapse;margin-top:8px}
          thead th{background:#f3f4f6;border:1px solid #e5e7eb;padding:8px;text-align:left;font-size:12px}
          tbody td{border:1px solid #e5e7eb;padding:8px;font-size:12px}
          td.num{text-align:right}
          .totals{margin-top:12px;display:flex;justify-content:flex-end}
          .totals-box{min-width:240px;border:1px solid #e5e7eb;border-radius:8px;padding:12px;background:#f9fafb}
          .row{display:flex;justify-content:space-between;margin:4px 0}
          .row.total{font-weight:600}
          .footer{margin-top:16px;font-size:12px;color:#6b7280;text-align:center}
          @media print{body{background:#fff} .sheet{border:none}}
        </style>
      </head>
      <body>
        <div class="sheet">
          <div class="header">
            <div class="brand">
              <img src="${logoUrl}" alt="Logo"/>
              <h1>${title}</h1>
            </div>
            <div class="meta">
              <div>Date: ${dateStr}</div>
              ${data.validUntil ? `<div>Valid Until: ${data.validUntil}</div>` : ''}
            </div>
          </div>
          <div class="grid">
            <div class="card">
              <div style="font-weight:600;margin-bottom:6px">Customer</div>
              <div>${data.client || data.customer || ''}</div>
            </div>
            <div class="card">
              <div style="font-weight:600;margin-bottom:6px">Reference</div>
              <div>${data.reference || ''}</div>
            </div>
          </div>
          <h2>Items</h2>
          <table>
            <thead>
              <tr>
                <th>Description</th>
                <th class="num">Qty</th>
                <th class="num">Unit</th>
                <th class="num">Total</th>
              </tr>
            </thead>
            <tbody>${rows}</tbody>
          </table>
          <div class="totals">
            <div class="totals-box">
              <div class="row"><span>Subtotal</span><span>${subtotal.toFixed(2)}</span></div>
              <div class="row"><span>Tax (${taxRate.toFixed(2)}%)</span><span>${taxAmount.toFixed(2)}</span></div>
              <div class="row"><span>Discount</span><span>${discount.toFixed(2)}</span></div>
              <div class="row total"><span>Total</span><span>${total.toFixed(2)}</span></div>
            </div>
          </div>
          <div class="footer">Generated by ProFlow</div>
        </div>
        <script>window.print && window.print()</script>
      </body>
      </html>`;
    const w = window.open('', '_blank');
    if (w) { w.document.write(html); w.document.close(); } else { alert('Pop-up blocked. Allow pop-ups to view.'); }
  } catch (err) {
    // Fallback error alert
    try { console.error('Failed to show quotation preview', err); } catch {}
    try { alert('Unable to preview quotation'); } catch {}
  }
}


